### ISSUE TITLE
Is swift-async-queue goal the same as Swift 5.9 custom Actor executor ?

### ISSUE THREAD

**Issue by gbitaudeau** [dfed/swift-async-queue#28]
According to https://developer.apple.com/videos/play/wwdc2023-10164/?time=2115 , in Swift 5.9, you can customize actor executor to use, for instance, a serial executor.

Does actor executor and swift-async-queue respond to the same purpose ?

If not, can you give us comparison points ?

**Comment by dfed** [comment]
The `swift-async-queue` is a layer on top of Swift Concurrency that enables enqueuing ordered tasks from nonisolated contexts. [The first section of the README](https://github.com/dfed/swift-async-queue?tab=readme-ov-file#task-ordering-and-swift-concurrency) describes the problem this library is solving well:

> While [actors](https://docs.swift.org/swift-book/LanguageGuide/Concurrency.html#ID645) are great at serializing tasks, there is no simple way in the standard Swift library to send ordered tasks to them from a synchronous context.

I do not believe custom actors solve this problem, but rather custom actors enable you to control where your actor is executing. That's a pretty different problem than controlling the order in which your enqueued tasks onto that actor execute.

Let me know if that answers your question!

**Comment by gbitaudeau** [comment]
Thanks, that's clear
